name: iOS Debug Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
      - name: Build Debug Simulator App
        working-directory: clients/ios/App
        run: |
          xcodebuild \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build
      - name: Archive build artifact
        working-directory: clients/ios/App
        run: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r App.app.zip App.app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: clients/ios/App/build/Build/Products/Debug-iphonesimulator/App.app.zip
